//Buffer Line
import { StyleSheet } from "react-native";
import { flex, center, row, iosBlue } from "./StyleSheetHelper";
import { theme } from "../theme/variables";

const AddPostPageStyleSheet = StyleSheet.create({
  postInputContainer: {
    flexDirection: row,
    alignItems: center,
    height: 43,
    width: "90%",
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    textDecorationLine: "none",
  },
  otherInputContainer: {
    flexDirection: row,
    height: "8%",
    width: "73%",
    marginLeft: "13%",
    marginBottom: 25,
    borderWidth: 1,
    borderRadius: 5.5,
    paddingLeft: 10,
    textDecorationLine: "none",
  },
  contentContainer: {
    flexDirection: row,
    alignItems: center,
    height: 200,
    width: "90%",
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    textDecorationLine: "none",
  },
  textInput: {
    width: 320,
  },
  postAgeContainer: {
    display: flex,
    justifyContent: "space-between",
    alignItems: center,
    height: 41,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  postCountryContainer: {
    display: flex,
    justifyContent: "space-between",
    alignItems: center,
    height: 41,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  ModalContainer: {
    display: flex,
    marginVertical: "10%",
    marginHorizontal: "10%",
    backgroundColor: "white",
    justifyContent: center,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  CountryScrollViewContainer: {
    width: "100%",
    height: "80%",
  },
  AgeScrollViewContainer: {
    width: "100%",
    height: "80%",
  },
  ModalButtonContainer: {
    display: flex,
    flexDirection: row,
    width: "100%",
    height: "10%",
    justifyContent: "space-evenly",
    alignItems: center,
  },
  ModalText: {
    paddingHorizontal: "45%",
    color: iosBlue,
    fontWeight: "bold",
    fontSize: 16,
    textAlign: center,
    alignItems: center,
    justifyContent: center,
  },
  addPost: {
    width: "90%",
    height: 60,
    margin: 12,
    padding: 10,
    display: flex,
    justifyContent: center,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: theme.button,
    backgroundColor: theme.button,
  },
  addPostText: {
    fontSize: 16,
    color: "#ffffff",
    textAlign: center,
    fontWeight: "bold",
    textShadowColor: "#8E8E8E",
    textShadowRadius: 1,
    textShadowOffset: {
      width: 0.9,
      height: 0.9,
    },
  },
  center: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    width: "100%",
  },
  typeContainer: {
    display: flex,
    justifyContent: "space-evenly",
    alignItems: center,
    width: "90%",
    height: 52,
    flexDirection: row,

    borderWidth: 1,
    borderRadius: 10,

    textDecorationLine: "none",
  },
  container: {
    flex: 1,
    height: "100%",
    width: "90%",
    // backgroundColor: "#ccaf9b",
    // padding: 20,
    alignItems: "center",
  },

  richTextContainer: {
    display: "flex",
    flexDirection: "column-reverse",
    width: "100%",
    marginBottom: 10,
  },

  richTextEditorStyle: {
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderWidth: 1,
    // borderColor: "#ccaf9b",
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.23,
    // shadowRadius: 2.62,
    elevation: 4,
    fontSize: 20,
  },

  richTextToolbarStyle: {
    // backgroundColor: "#c6c3b3",
    // borderColor: "#c6c3b3",
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },

  errorTextStyle: {
    color: "#FF0000",
    marginBottom: 10,
  },
});

export default AddPostPageStyleSheet;
