import { StyleSheet } from "react-native";
import { theme } from "../theme/variables";
import { center, flex, iosBlue, row, white } from "./StyleSheetHelper";

const ManageTourScreenStyleSheet = StyleSheet.create({
  postDetailContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: 10,
  },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 50,
    resizeMode: "contain",
    marginRight: 10,
  },
  row: {
    flexDirection: "row",
    marginRight: 10,
    flexWrap: "wrap",
    gap: 6,
  },
  rowContent: {
    flexDirection: "row",
    marginRight: 10,
    paddingTop: 5,
    paddingBottom: 5,
    flexWrap: "wrap",
  },
  contentContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "white",
    flex: 1,
  },
  titleKey: { fontWeight: "600" },
  button: {
    width: 55,
    height: 33,
    marginRight: 5,
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: theme.primaryColor,
    backgroundColor: theme.primaryColor,
  },
  rejectButton: {
    width: 55,
    height: 33,
    marginRight: 8,
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "red",
    backgroundColor: "red",
  },
  text: {
    fontSize: 14,
    color: theme.primaryTextColor,
    textAlign: "center",
  },
  statusText: {
    fontSize: 14,
    marginRight: 13,
    color: "black",
    textAlign: "center",
  },
  planButton: {
    height: 50,
    marginRight: 2,
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: theme.primaryColor,
    backgroundColor: theme.primaryColor,
  },
  planCloseButton: {
    height: 50,
    marginRight: 2,
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "red",
    backgroundColor: "red",
  },
  planButtonText: {
    fontSize: 18,
    color: theme.primaryTextColor,
    textAlign: "center",
  },
  modalContainer: {
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  modalContent: {
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    position: "absolute",
    top: 150,
    right: 20,
    zIndex: 1,
  },
  ModalButtonContainer: {
    display: flex,
    flexDirection: row,
    width: "100%",
    height: "10%",
    justifyContent: "space-evenly",
    alignItems: center,
  },
  ModalText: {
    paddingHorizontal: "30%",
    color: iosBlue,
    fontWeight: "bold",
    fontSize: 22,
    textAlign: center,
    alignItems: center,
    justifyContent: center,
  },
  container: {
    alignItems: "center",
    paddingBottom: 5,
  },
  AvatarContainer: {
    position: "relative",
    marginBottom: 5,
  },
  TitleText: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 5,
  },
});

export default ManageTourScreenStyleSheet;
