import { StyleSheet } from "react-native";
import { center, flex, full, iosBlue, row, white } from "./StyleSheetHelper";

const PlanningStyleSheet = StyleSheet.create({
  center: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    width: full,
    flexDirection: row,
  },
  inputTitle: {
    fontWeight: "800",
    fontSize: 24,
    marginLeft: 8,
  },
  inputContainer: {
    width: "95%",
    height: 24,
    marginLeft: 8,
    marginTop: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
  },
  daySelectCon: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    height: 50,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  uploadContainerSquare: {
    elevation: 2,
    height: 300,
    width: 400,
    backgroundColor: "#efefef",
    position: "relative",
    overflow: "hidden",
    marginBottom: 12,
    justifyContent: center,
  },
  uploadBtnContainerSquare: {
    opacity: 0.7,
    position: "absolute",
    right: 0,
    bottom: 0,
    backgroundColor: "lightgrey",
    width: "100%",
    height: "15%",
    color: "red",
    justifyContent: center,
    alignItems: center,
  },
  backgroundColor: {
    backgroundColor: "#ffffff",
  },
  uploadBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  countryContainer: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    height: 50,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  ModalButtonContainer: {
    display: flex,
    flexDirection: row,
    width: "100%",
    height: "10%",
    justifyContent: center,
    alignItems: center,
  },
  ModalText: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 8,
    color: iosBlue,
    fontWeight: "bold",
    fontSize: 16,
    textAlign: center,
    alignItems: center,
    justifyContent: center,
  },
  AddScheduleSytle: {
    height: 1000,
  },
  buttonStyle: {
    width: "90%",
    height: 60,
    margin: 12,
    padding: 10,
    display: flex,
    justifyContent: center,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: iosBlue,
    backgroundColor: iosBlue,
  },
  loginText: {
    fontSize: 16,
    color: "#ffffff",
    textAlign: center,
  },
});

export default PlanningStyleSheet;
