//Buffer Line
import { StatusBar, StyleSheet } from "react-native";
import { flex, center, row, full, iosBlue } from "./StyleSheetHelper";

const RegisterPageStyleSheet = StyleSheet.create({
  center: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    width: "100%",
    flexDirection: row,
  },
  inputContainer: {
    flexDirection: row,
    alignItems: center,
  },
  outerContainer: {
    height: 60,
    width: "90%",
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    textDecorationLine: "none",
  },

  textInput: {
    width: 320,
    // marginLeft: 8,
  },
  passwordContainer: {
    // display: flex,
    // justifyContent: center,
    // alignItems: center,
    width: "90%",
    flexDirection: row,
    flexWrap: "wrap",
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    textDecorationLine: "none",
  },
  password: {
    flexDirection: row,
    alignItems: center,
    // width: "100%",
    // margin: 8,
  },
  genderContainer: {
    display: flex,
    justifyContent: "space-evenly",
    alignItems: center,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  birthdayContainer: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    height: 50,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  countryContainer: {
    display: flex,
    justifyContent: center,
    alignItems: center,
    height: 50,
    width: "90%",
    flexDirection: row,
    margin: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    textDecorationLine: "none",
  },
  ModalContainer: {
    display: flex,
    marginVertical: "25%",
    marginHorizontal: "10%",
    backgroundColor: "white",
    justifyContent: center,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  BirthdayModalContainer: {
    display: flex,
    marginTop: "45%",
    marginBottom: "50%",
    marginHorizontal: "10%",
    backgroundColor: "white",
    justifyContent: center,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  CountryScrollViewContainer: {
    width: "100%",
    height: "80%",
  },
  BirthdayScrollViewContainer: {
    width: "100%",
    height: "80%",
  },
  ModalButtonContainer: {
    display: flex,
    flexDirection: row,
    width: "100%",
    height: "10%",
    justifyContent: "space-evenly",
    alignItems: center,
  },
  ModalText: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 8,
    color: iosBlue,
    fontWeight: "bold",
    fontSize: 16,
    textAlign: center,
    alignItems: center,
    justifyContent: center,
    // backgroundColor: "red",
  },
  uploadContainer: {
    elevation: 2,
    height: 150,
    width: 150,
    backgroundColor: "#efefef",
    position: "relative",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 12,
  },
  uploadBtnContainer: {
    opacity: 0.7,
    position: "absolute",
    right: 0,
    bottom: 0,
    backgroundColor: "lightgrey",
    width: "100%",
    height: "25%",
  },
  uploadBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  item: {
    backgroundColor: "#f9c2ff",
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 32,
  },
  uploadContainerSquare: {
    elevation: 2,
    height: 300,
    width: 400,
    backgroundColor: "#efefef",
    position: "relative",
    overflow: "hidden",
    marginBottom: 12,
  },
  uploadBtnContainerSquare: {
    opacity: 0.7,
    position: "absolute",
    right: 0,
    bottom: 0,
    backgroundColor: "lightgrey",
    width: "100%",
    height: "15%",
  },
});

export default RegisterPageStyleSheet;
